# app.yaml
runtime: python310
entrypoint: uvicorn mysite.asgi:application --host 0.0.0.0 --port $PORT

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "your_project_name.settings"

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
